# Generated by Django 5.0.4 on 2024-04-27 03:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Paaark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("noplate", models.CharField(max_length=50)),
                (
                    "modifiednoplate",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("engine_number", models.CharField(max_length=20)),
                ("chassis_number", models.CharField(max_length=20)),
                ("insurance_details", models.TextField()),
                ("contact_number", models.CharField(max_length=15)),
                ("email_address", models.EmailField(max_length=254)),
                ("owner", models.CharField(max_length=100)),
                ("color", models.CharField(max_length=50)),
                ("bluebook_expiry_date", models.DateField()),
                ("category", models.CharField(max_length=1)),
            ],
        ),
    ]
