# Generated by Django 5.0.4 on 2024-04-27 04:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_paaark"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Paark",
        ),
    ]
